# Generated by Django 2.2.19 on 2022-04-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220414_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredientamount', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
    ]
